version: 2
updates:
  - package-ecosystem: pip
    directory: "/backend/api_server"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
