from enum import StrEnum

class Role(StrEnum):
    OWNER = "OWNER"
    MANAGER = "MANAGER"
    CASHIER = "CASHIER"
    SALES = "SALES"
    TECHNICIAN = "TECHNICIAN"
    ACCOUNTANT = "ACCOUNTANT"
    INVENTORY = "INVENTORY"
    BRANCH_MANAGER = "BRANCH_MANAGER"

class ProductType(StrEnum):
    PHONE_NEW = "PHONE_NEW"
    PHONE_USED = "PHONE_USED"
    ACCESSORY = "ACCESSORY"
    SPARE_PART = "SPARE_PART"
    SERVICE = "SERVICE"

class ProductUnitStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    SOLD = "SOLD"
    RETURNED = "RETURNED"
    MAINTENANCE = "MAINTENANCE"
    DAMAGED = "DAMAGED"
    TRANSFERRED = "TRANSFERRED"

class EventType(StrEnum):
    SALE = "SALE"
    PURCHASE = "PURCHASE"
    PAYMENT = "PAYMENT"
    EXPENSE = "EXPENSE"
    TRANSFER = "TRANSFER"
    RETURN = "RETURN"
    MAINTENANCE = "MAINTENANCE"
    INSTALLMENT_COLLECTION = "INSTALLMENT_COLLECTION"
    WALLET_MOVEMENT = "WALLET_MOVEMENT"
    STOCK_MOVEMENT = "STOCK_MOVEMENT"
    ADJUSTMENT = "ADJUSTMENT"
    REVERSAL = "REVERSAL"
